import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import worker,{validateBooking,isValidDate} from '../server/worker.js';
const now=new Date('2026-09-17T04:00:00Z');
const booking={appId:'stocklist',date:'2026-09-18',slot:'11:00',name:'Test User',email:'test@example.com',company:'Test'};
test('weekday, time, contact and past-date validation',()=>{assert.equal(validateBooking(booking,now),null);for(const change of [{date:'2026-09-19'},{date:'2026-09-20'},{slot:'13:00'},{slot:'16:30'},{email:'bad'},{appId:'unknown'},{date:'2026-02-31'},{date:'2026-09-16'}])assert.ok(validateBooking({...booking,...change},now));assert.equal(isValidDate('2026-09-18',now),true)});
test('database rejects duplicate studio slots across apps and API protects contact data',async()=>{const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('drizzle/0000_keen_tarantula.sql','utf8'));const DB={prepare(sql){return{bind(...values){return{async all(){return{results:db.prepare(sql).all(...values)}},async run(){return db.prepare(sql).run(...values)}}}}}};let day=new Date(Date.now()+86400000);while([0,6].includes(day.getUTCDay()))day=new Date(+day+86400000);const payload={...booking,date:day.toISOString().slice(0,10)};const request=b=>new Request('https://studio.test/api/bookings',{method:'POST',headers:{Origin:'https://studio.test','Content-Type':'application/json'},body:JSON.stringify(b)});const first=await worker.fetch(request(payload),{DB});assert.equal(first.status,201);assert.ok((await first.json()).id);const second=await worker.fetch(request({...payload,appId:'minicrm'}),{DB});assert.equal(second.status,409);const availability=await worker.fetch(new Request('https://studio.test/api/availability?date='+payload.date),{DB});const response=await availability.json();assert.equal(response.slots.find(s=>s.time==='11:00').available,false);assert.equal(JSON.stringify(response).includes(payload.email),false);const missingDB=await worker.fetch(new Request('https://studio.test/api/availability?date='+payload.date),{});assert.equal(missingDB.status,503);db.close()});
