// Server-only adapter for the queries used by the shared booking handler.
export function supabaseDatabase(env) {
 const base=env.SUPABASE_URL, key=env.SUPABASE_SECRET_KEY;
 if(!base||!key)throw Error('Supabase is not configured');
 const headers={apikey:key,'Content-Type':'application/json'};
 if(!key.startsWith('sb_secret_'))headers.Authorization='Bearer '+key;
 async function call(path,options={}){const r=await fetch(base.replace(/\/$/,'')+'/rest/v1/'+path,{...options,headers:{...headers,...options.headers}});const text=await r.text();const data=text?JSON.parse(text):null;if(!r.ok){if(data?.code==='23505')throw Error('UNIQUE constraint');throw Error('Database request failed: '+r.status)}return data;}
 function prepare(sql){return {bind(...v){return {async all(){let path;if(sql==='SELECT slot FROM bookings WHERE date = ?')path='bookings?select=slot&date=eq.'+encodeURIComponent(v[0]);else if(sql==='SELECT slot, visible, active FROM availability WHERE date = ?')path='availability?select=slot,visible,active&date=eq.'+encodeURIComponent(v[0]);else if(sql==='SELECT date, slot, visible, active FROM availability WHERE date >= ? AND date <= ?')path='availability?select=date,slot,visible,active&date=gte.'+encodeURIComponent(v[0])+'&date=lte.'+encodeURIComponent(v[1]);else throw Error('Unsupported query');return {results:await call(path)}},async run(){if(!sql.startsWith('INSERT INTO bookings'))throw Error('Unsupported mutation');const saved=await call('rpc/book_session',{method:'POST',body:JSON.stringify({p_id:v[0],p_app:v[1],p_date:v[2],p_slot:v[3],p_name:v[4],p_email:v[5],p_company:v[6]})});return {meta:{changes:saved?1:0}}},sql,values:v}}}}
 return {prepare,async batch(statements){if(statements.some(s=>!s.sql.startsWith('INSERT INTO availability')))throw Error('Unsupported batch');return call('rpc/save_availability',{method:'POST',body:JSON.stringify({p_date:statements[0].values[0],p_slots:statements.map(s=>({slot:s.values[1],visible:s.values[2],active:s.values[3]}))})});}};
}
